### ISSUE TITLE
Connection time ou

### ISSUE THREAD

**Issue by DiegoECQ** [stormpath/stormpath-spring-boot-react-example#2]
I have this error when i execute mvn spring-boot:run

![image](https://cloud.githubusercontent.com/assets/19826929/23414388/19691732-fdb2-11e6-8c69-aab22f774774.png)

Can you help me, please?

**Comment by kewp** [comment]
hi there.

not sure what's going on. did you change anything in the source

**Comment by DiegoECQ** [comment]
What should I put in the href section?
stormpath.application.href =

**Comment by kewp** [comment]
Do you have a Stormpath account ? There you put in the href for your application. https://docs.stormpath.com/java/servlet-plugin/_images/console-application-href.png

**Comment by DiegoECQ** [comment]
Wich is the password?

![image](https://cloud.githubusercontent.com/assets/19826929/23415943/461d1850-fdb7-11e6-87e7-b40f9c6b2402.png)

**Comment by kewp** [comment]
Do you mean the key and secret, the other two fields in `application.properties` ?

Those you download at the front of the admin console. https://stormpath.com/images/blog/lumen/Manage-API-Key.png

**Comment by DiegoECQ** [comment]
OK, so wich is apikey.SECRET?

**Comment by kewp** [comment]
When you download the api key it comes in the apiKey.properties file. https://docs.stormpath.com/rest/product-guide/latest/quickstart.html#create-an-api-key-pair

**Comment by DiegoECQ** [comment]
I have the same error:
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_112]

I copy the file to \.stormpath.
and i put the same key and pass in application.properties

**Comment by kewp** [comment]
Did you mean to close the issue ?

Not sure what is causing the timeout. Did you resolve it ?
