### ISSUE TITLE
Unable to build under MacOS environment

### ISSUE THREAD

**Issue by mxmingya** [stormpath/stormpath-spring-boot-react-example#5]
Having errors like 
```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
```
in the phase of 
```
ERROR 89311 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed
```

**Comment by mraible** [comment]
The Stormpath API was shutdown in August 2017, so this example is unlikely to work. I'd recommend reading [Bootiful Development with Spring Boot and React](https://developer.okta.com/blog/2017/12/06/bootiful-development-with-spring-boot-and-react) as an alternative. 

You can find its example app at https://github.com/oktadeveloper/spring-boot-react-example.
